### PR TITLE
Feature/wid 325 upgrade angular

### PR DESCRIPTION
**Pull request by simon-debruijn**
### Changed
- Upgrade to Angular 11
- Use ESlint instead of depricated TSlint
- Use prettier as formatter
- Use newer version of bootstrap and change tabset to be [nav](https://ng-bootstrap.github.io/#/components/nav/overview)

### Fixed
- A lot of eslint and typescript errors

### Removed
- Old test suites
- tests that were barely doing anything

---
Ticket: https://jira.uitdatabank.be/browse/WID-325

Related PR: https://github.com/cultuurnet/projectaanvraag-vagrant/pull/9

### CODE REVIEW

**Comment by bertramakers** [comment]
I started going through the commits but have to admit that I don't understand half of the changes so far. @brampauwelyn do you have some time to review this?

**Review by brampauwelyn — CHANGES_REQUESTED** [review]
**"fa fa-arrows drag"**  seems to be missing.
probably related to the font-awesome upgrade?

Screenshot 2021-04-13 at 09 51 46


The setting menu isn't showing properly...
Screenshot 2021-04-13 at 09 53 31


Something goes wrong while trying to modify the css of a widget
Screenshot 2021-04-13 at 09 56 48

Changing the theme of a widget doesn't work (modal should close + style should be applied).
Screenshot 2021-04-13 at 10 04 23

**Comment by simon-debruijn** [comment]
@brampauwelyn The issues mentioned above should be fixed

**Review by brampauwelyn — COMMENTED** [review]
I guess we should also change this in Jenkins when we merge this.
To discuss with @willaerk.

**Review by brampauwelyn — APPROVED** [review]

**Pull request merged**
